### ISSUE TITLE
Where is the questions_with_correct.json?

### ISSUE THREAD

**Issue by TousakaNagio** [egoschema/EgoSchema#1]
Hi, 

Thank you for your great work.
I am trying to reproduce the benchmarking of InternVideo,
however, I can't really understand the installation step of InternVideo.
Also, I can't find the "questions_with_correct.json" from the benchmarking/InternVideo/disguise.ipynb.
Would you please clarify this for me?

Thank you very much.

Best Regard,
TousakaNagio

**Comment by egoschema** [comment]
Hello Tousaka

I am so sorry for the late reply, I have been out of the grid for the last week. I am currently reformating the benchmarking code to work without the correct answers as well as clarifying the steps in the instructions. The changes will be pushed by the end of today.
Thank you
Raiymbek

**Comment by egoschema** [comment]
Hello TousakaNagio

I fixed the instructions for reproducing the InteructionVid results on Egoschema. Please let me know if it works for you and if you have any questions. Please make sure to follow their installation instructions on both the main readme and the multi-modalities-downstream readme.
Thank you
Raiymbek
