### ISSUE TITLE
Failed for validation 

### ISSUE THREAD

**Issue by Ziyang412** [egoschema/EgoSchema#11]
Hi, thanks for the great work! 

I am trying to test our model on your "Option B (using our provided wrapper): No leaderboard, just a submission validation." and I received the error below:
```
Response Status Code: 500
Response Content:
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

It seems like the server is not working, could you help me with that? Thanks a lot!

**Comment by egoschema** [comment]
Hello, I just tested the server it works fine for me, maybe there is something wrong with the JSON file?
