### ISSUE TITLE
Timestamps and narrations of the video.

### ISSUE THREAD

**Issue by zhousheng97** [egoschema/EgoSchema#13]
Thank you for your excellent work. I want to conduct further research specifically on the QA generation. If possible, could you please provide the timestamps and narrations corresponding to each video in the Egoschema dataset?

**Comment by egoschema** [comment]
added it.

**Comment by lqh52** [comment]
Hi, thank you for your excellent work. Could you please let me know where I can find the narrations corresponding to each video?
