### ISSUE TITLE
Regarding the Google Drive data

### ISSUE THREAD

**Issue by TalalWasim** [egoschema/EgoSchema#2]
Hi,

I had a quick question regarding the google drive download link.

Whats the difference between the videos.tar.gz and Egochema_videos folder? Are they the same thing?

Talal

**Comment by egoschema** [comment]
Hello TalalWasim

Yeah videos.tar.gz is just a folder with all egoschema videos. 
Thanks

**Comment by egoschema** [comment]
You probably got the good_clips_git folder after you untarred it. I will fix it, this is the same folder as the videos folder should be.
