### ISSUE TITLE
Evaluation server seems down

### ISSUE THREAD

**Issue by chaitanya100100** [egoschema/EgoSchema#20]
Hello,

It looks like evaluation server is down. When I run `python validate.py --f <path_to_json_file>` , I get server error with `Response Status Code: 500` response. The same json file was working a while back. Can you please look into it?

**Comment by egoschema** [comment]
I don't see anything wrong with the server. You might need to run validate.py a couple times it seems to wait for the server to start.

**Comment by chaitanya100100** [comment]
Yes. It looks like server goes through intermittent failures in between.
