### ISSUE TITLE
How to determine the certificate length for multiple non-contiguous certificates that are far apart?

### ISSUE THREAD

**Issue by fake-warrior8** [egoschema/EgoSchema#3]
Hi, I'd like to know how to determine the certificate length for multiple non-contiguous certificates that are far apart (>5 seconds apart). I do not understand what 'make a reasonable judgement' means. whether you add up the lengths of these non-contiguous certificates, or just use the total interval length of these non-contiguous certificates?

![T@A~}P1Z4P){D$FT6X6RVMH](https://github.com/egoschema/EgoSchema/assets/40395156/dbd760d4-6190-456d-bb07-3d7152645f17)

**Comment by egoschema** [comment]
Hello, I'm sorry for not getting back to you sooner. In the case of multiple non-contiguous certificates, you should add it up if the certificates are enough to 100% find the correct answer. Think of it like cutting the video to only the certificate parts and seeing if that would be enough.
