### ISSUE TITLE
How to identify the certificate length of a VQA？

### ISSUE THREAD

**Issue by GanJayjay** [egoschema/EgoSchema#8]
Hello，
Thanks for sharing this great work!
I wonder how you measure the cetificate length of a VQA. In your paper, you filtered the dataset based on the certificate length and also measured the certificate length for other existed datasets. How do you achieve this? Is it a manual process? Or did you use LLM to measure it. If so, how do you achive it?

**Comment by egoschema** [comment]
Hello 

We mainly used human labeling to label the certificate length but we limited the amount of human hours spent on each dataset. Human labelers had to answer what part of the video was minimally sufficient to answer the question. In a lot of cases for some datasets, even 1 sec is enough to find the answer.
