### ISSUE TITLE
 the details of different LLMs' response

### ISSUE THREAD

**Issue by sunwhw** [egoschema/EgoSchema#9]
Thanks  for your great work! I wanna know the details of different LLMs response, but I can't find the _supplementary_
<img width="724" alt="image" src="https://github.com/egoschema/EgoSchema/assets/48038000/83b9f1b2-97a6-44c2-a9a6-da5444aa2b7f">

**Comment by egoschema** [comment]
The paper version on the arxiv has the supplementary after the references. It contains some examples of prompts and models's output of those prompts
